# Generated by Django 3.2.25 on 2024-11-28 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_auto_20241128_1318'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserMembership',
        ),
    ]
