# Generated by Django 3.2.25 on 2024-11-29 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0007_membershiporder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MembershipOrder',
        ),
    ]
