# Generated by Django 3.2.25 on 2024-11-28 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0006_delete_usermembership'),
        ('checkout', '0004_auto_20241127_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='membership',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='membership.membership'),
            preserve_default=False,
        ),
    ]
