# Generated by Django 3.2.25 on 2024-11-28 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_order_membership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='membership',
        ),
    ]
