# Generated by Django 3.2.25 on 2025-03-16 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_class', '0003_alter_fitnessclass_day'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
